/* Autogenerated by png2wx.pl on Wed Oct 14 00:12:53 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_projections;

#endif /* ICONS_H */
