/* Autogenerated by png2wx.pl on Tue Mar  1 07:09:45 2016 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_projections;

#endif /* ICONS_H */
